version: '3.8'

services:
  portal:
    image: careful:latest
    ports:
      - "3000:80"  
    restart: always
    depends_on:
      - eep_server

  eep_server:
    image: endpoint:latest
    ports:
      - "9000:9000"
    restart: always
    depends_on:
      - drug_detector
      - xai
      - rag_server
    environment:
      - DRUG_DETECTOR_URL=http://drug_detector:5000
      - XAI_URL=http://xai:5001
      - RAG_URL=http://rag_server:8000

  drug_detector:
    image: detector:latest
    ports:
      - "5000:5000"
    restart: always

  xai:
    image: xai:latest
    ports:
      - "5001:5001"
    restart: always

  rag_server:
    image: psyprotectionregistry.azurecr.io/psyrag:latest
    ports:
      - "8000:8000"
    restart: always
