version: '3.8'
services:
  rag_server:
    image: olasadek/psyrag:production
    ports:
      - "8000:8000"
    restart: always
    environment:
      - openai_api_key=${OPENAI_API_KEY}
      - entrez_email=${ENTREZ_EMAIL}


secrets:
  openai_api_key:
    file: ./secrets/openai_api_key.txt
  entrez_email:
    file: ./secrets/entrez_email.txt
