apiVersion: apps/v1
kind: Deployment
metadata:
  name: drug-detector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drug-detector
  template:
    metadata:
      labels:
        app: drug-detector
    spec:
      containers:
        - name: drug-detector
          image: abuse1.azurecr.io/multimodal-drug-detector:latest
          ports:
            - containerPort: 5000
---
# drug_detector.yaml, xai.yaml, rag_server.yaml
apiVersion: v1
kind: Service
metadata:
  name: service-name
spec:
  type: ClusterIP  
  ports:
    - port: [5000]
      targetPort: [5000]
  selector:
    app: [drug-detector]
    app: drug-detector
