apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: portal-server
  template:
    metadata:
      labels:
        app: portal-server
    spec:
      containers:
        - name: portal
          image: olasadek/careful:latest
          ports:
            - containerPort: 80
          env:
            - name: EEP_SERVER_URL  # Portal talks ONLY to EEP
              value: "http://eep-server:9000"
---
apiVersion: v1
kind: Service
metadata:
  name: portal-server
spec:
  type: LoadBalancer  # Public endpoint
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: portal-server
