apiVersion: apps/v1
kind: Deployment
metadata:
  name: rag-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rag-server
  template:
    metadata:
      labels:
        app: rag-server
    spec:
      containers:
        - name: rag-server
          image: olasadek/psyrag:production
          ports:
            - containerPort: 8000
          env:
            - name: openai_api_key
              value: ${OPENAI_API_KEY}
            - name: entrez_email
              value: ${ENTREZ_EMAIL}
---
apiVersion: v1
kind: Service
metadata:
  name: rag-server
spec:
  ports:
    - port: 8000
  selector:
    app: rag-server
