apiVersion: apps/v1
kind: Deployment
metadata:
  name: xai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xai
  template:
    metadata:
      labels:
        app: xai
    spec:
      containers:
        - name: xai
          image: abuse.azurecr.io/xai:latest
          ports:
            - containerPort: 5001
---
# drug_detector.yaml, xai.yaml, rag_server.yaml
apiVersion: v1
kind: Service
metadata:
  name: service-name
spec:
  type: ClusterIP  # Default - no change needed
  ports:
    - port: [5001]
      targetPort: [5001]
  selector:
    app: [xai]
