apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portal-server
  template:
    metadata:
      labels:
        app: portal-server
    spec:
      containers:
        - name: portal-server
          image: olasadek/careful:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: portal-server
spec:
  ports:
    - port: 80
  selector:
    app: portal-server
