name: Check All Python Requirements

on:
  push:
    paths:
      - '**/requirements*.txt'
      - '.github/workflows/check-requirements.yml'
  pull_request:
    paths:
      - '**/requirements*.txt'

jobs:
  check-requirements:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Find and check all requirements files
      run: |
        python -m pip install --upgrade pip
        find . -type f -name "requirements*.txt" | while read reqfile; do
          echo "Checking $reqfile"
          pip install -r "$reqfile"
        done
